# Generated by Django 6.1.1 on 2026-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dm_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone (message requests for non-followers)'), ('followers', 'Only people I follow'), ('nobody', 'No one')], default='everyone', max_length=10),
        ),
    ]
